name: Build EXE for Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pyinstaller and dependencies
        run: |
          pip install pyinstaller pandas openpyxl

      - name: Build EXE
        run: pyinstaller --onefile --windowed --icon=sloth.ico --name="give_me_my_network" table_merger_step6.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: give_me_my_network_exe
          path: dist/give_me_my_network.exe
